"""BibTeX enrichment via CrossRef.

The :mod:`tex_export` module emits ``paper/references.bib`` with
``journal = {[TODO: journal]}`` placeholders because the project
``literature_catalog`` deliberately stores only the minimum metadata
needed for the research narrative (author, title, year, market focus,
method focus, narrative camp). Real journals — RFS, JFE, JFQA, JBF, MS,
JF — reject submissions whose bibliography omits the full citation
(journal name, volume, issue, pages, DOI). The author of this project
should not be manually retyping 16 bibliographies the night before a
desk-submission deadline.

This module fills in those fields by querying CrossRef
(see :mod:`crossref_client`) for each ``@article`` entry, scoring the
returned candidates by author-surname overlap + title token Jaccard,
and only filling in the bibliography when the score meets a
configurable confidence threshold (default 0.7).

Design contract:

- **Preserve user-authored data.** Original ``title`` / ``author`` /
  ``year`` are never overwritten — they're what the researcher chose
  to cite. CrossRef is only consulted for fields that were
  ``[TODO: ...]`` placeholders or absent.
- **Idempotent.** Running the CLI twice produces identical output.
  CrossRef responses are cached to disk
  (default ``cache/crossref_cache.json``).
- **Low-confidence stays TODO.** Below ``min_confidence``, the entry
  retains its original placeholder. The enrichment report flags it so
  the author can decide whether to fill it in manually.
- **Network resilient.** CrossRef being down → every entry low-confidence
  → output bib equals input bib (modulo whitespace). No exception
  escapes :func:`enrich_references_bib`.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections.abc import Sequence
from dataclasses import asdict, dataclass, field
from pathlib import Path

from index_inclusion_research import paths
from index_inclusion_research.crossref_client import (
    CrossRefClient,
    CrossRefResult,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants & defaults
# ---------------------------------------------------------------------------


DEFAULT_MIN_CONFIDENCE = 0.7


def _default_input_bib() -> Path:
    return paths.project_root() / "paper" / "references.bib"


def _default_output_bib() -> Path:
    return paths.project_root() / "paper" / "references.enriched.bib"


def _default_cache_path() -> Path:
    return paths.project_root() / "cache" / "crossref_cache.json"


# ---------------------------------------------------------------------------
# BibTeX entry parsing
# ---------------------------------------------------------------------------


# Single ``@article{key, field = value, ...}`` block. We deliberately
# write a permissive regex: real BibTeX has a richer grammar but the
# files we emit are well-formed and stable, generated by
# :func:`tex_export.build_bibtex_from_catalog`. Anything we don't
# recognize is passed through unchanged.
_ENTRY_PATTERN = re.compile(
    r"@(?P<type>\w+)\s*\{\s*(?P<key>[^,\s]+)\s*,(?P<body>.*?)\n\}",
    re.DOTALL,
)

_FIELD_PATTERN = re.compile(
    r"^\s*(?P<name>\w+)\s*=\s*\{(?P<value>.*?)\}\s*,?\s*$",
    re.MULTILINE | re.DOTALL,
)


@dataclass
class BibEntry:
    """One parsed BibTeX ``@article{...}`` entry."""

    entry_type: str
    citation_key: str
    fields: dict[str, str] = field(default_factory=dict)

    def has_todo(self, field_name: str) -> bool:
        value = self.fields.get(field_name, "")
        return value.startswith("[TODO:") or value == ""

    def author(self) -> str:
        return self.fields.get("author", "")

    def title(self) -> str:
        return self.fields.get("title", "")

    def year_int(self) -> int | None:
        raw = self.fields.get("year", "")
        digits = "".join(ch for ch in raw if ch.isdigit())
        if len(digits) >= 4:
            return int(digits[:4])
        return None


def _parse_bib(text: str) -> list[BibEntry]:
    """Parse a BibTeX file into a list of :class:`BibEntry`.

    The parser is intentionally lenient — it ignores entries with field
    syntax it can't match (comments, ``@string``, etc.). For the
    auto-generated paper bib that's a non-issue because every entry is
    a uniformly formatted ``@article``.
    """
    entries: list[BibEntry] = []
    for match in _ENTRY_PATTERN.finditer(text):
        body = match.group("body")
        fields_dict: dict[str, str] = {}
        for fm in _FIELD_PATTERN.finditer(body):
            value = fm.group("value").strip()
            # Strip leading/trailing whitespace + newlines that BibTeX
            # field values sometimes pick up when the brace spans lines.
            fields_dict[fm.group("name").strip()] = re.sub(r"\s+", " ", value)
        entries.append(
            BibEntry(
                entry_type=match.group("type"),
                citation_key=match.group("key"),
                fields=fields_dict,
            )
        )
    return entries


def _format_entry(entry: BibEntry) -> str:
    """Render a :class:`BibEntry` back to BibTeX source.

    The field order is fixed (author, title, year, journal, volume,
    issue, pages, doi, note) so the rendered output is deterministic
    regardless of the dict iteration order. Unknown fields fall to the
    end in alphabetical order.
    """
    ordered_keys = [
        "author",
        "title",
        "year",
        "journal",
        "volume",
        "issue",
        "pages",
        "doi",
        "note",
    ]
    seen: set[str] = set()
    parts = [f"@{entry.entry_type}{{{entry.citation_key},"]
    for key in ordered_keys:
        if key in entry.fields:
            parts.append(f"  {key:<9} = {{{entry.fields[key]}}},")
            seen.add(key)
    for key in sorted(entry.fields):
        if key in seen:
            continue
        parts.append(f"  {key:<9} = {{{entry.fields[key]}}},")
    parts.append("}")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------


@dataclass
class CrossRefCache:
    """On-disk cache for CrossRef query results.

    The cache key is ``citation_key + "|" + title + "|" + year``, so
    rerunning enrichment after an unrelated entry was added doesn't
    re-fire all 16 HTTP requests.

    The on-disk format is a plain JSON dict mapping cache-keys to
    serialized :class:`CrossRefResult` payloads. ``None`` results (no
    match) are also cached as ``{"status": "miss"}`` so we don't retry
    every run.
    """

    path: Path
    _data: dict[str, dict[str, object] | None] = field(
        default_factory=dict, repr=False
    )

    def load(self) -> None:
        if not self.path.exists():
            return
        try:
            self._data = json.loads(self.path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("CrossRef cache load failed: %s; starting fresh", exc)
            self._data = {}

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(self._data, ensure_ascii=False, indent=2, sort_keys=True),
            encoding="utf-8",
        )

    def _make_key(self, entry: BibEntry) -> str:
        title = re.sub(r"\s+", " ", entry.title()).strip().lower()
        year = entry.year_int() or 0
        return f"{entry.citation_key}|{title}|{year}"

    def get(self, entry: BibEntry) -> CrossRefResult | None | str:
        """Return cached result, sentinel ``"miss"`` for cached misses, or ``None``."""
        key = self._make_key(entry)
        if key not in self._data:
            return None
        payload = self._data[key]
        if payload is None:
            return None
        if isinstance(payload, dict) and payload.get("status") == "miss":
            return "miss"
        if isinstance(payload, dict) and "doi" in payload:
            year_raw = payload.get("year")
            year_value: int | None
            if isinstance(year_raw, int):
                year_value = year_raw
            elif isinstance(year_raw, str) and year_raw.isdigit():
                year_value = int(year_raw)
            else:
                year_value = None
            confidence_raw = payload.get("confidence_score", 0.0)
            confidence_value = (
                float(confidence_raw)
                if isinstance(confidence_raw, (int, float, str))
                else 0.0
            )
            return CrossRefResult(
                doi=str(payload.get("doi", "")),
                journal=str(payload.get("journal", "")),
                volume=str(payload.get("volume", "")),
                issue=str(payload.get("issue", "")),
                pages=str(payload.get("pages", "")),
                year=year_value,
                title_matched=str(payload.get("title_matched", "")),
                author_matched=str(payload.get("author_matched", "")),
                confidence_score=confidence_value,
            )
        return None

    def put(self, entry: BibEntry, result: CrossRefResult | None) -> None:
        key = self._make_key(entry)
        if result is None:
            self._data[key] = {"status": "miss"}
        else:
            self._data[key] = asdict(result)


# ---------------------------------------------------------------------------
# Enrichment report
# ---------------------------------------------------------------------------


@dataclass
class EntryEnrichment:
    """Per-entry outcome of an enrichment run."""

    citation_key: str
    title: str
    status: str  # "enriched" | "kept_todo_low_confidence" | "kept_todo_no_match" | "skipped_no_todo"
    confidence_score: float
    doi: str = ""
    journal: str = ""


@dataclass
class EnrichmentReport:
    """Summary of a single :func:`enrich_references_bib` run."""

    entries: list[EntryEnrichment] = field(default_factory=list)

    def enriched_count(self) -> int:
        return sum(1 for e in self.entries if e.status == "enriched")

    def kept_todo_count(self) -> int:
        return sum(1 for e in self.entries if e.status.startswith("kept_todo"))

    def skipped_count(self) -> int:
        return sum(1 for e in self.entries if e.status == "skipped_no_todo")

    def as_text(self) -> str:
        lines: list[str] = []
        for e in self.entries:
            lines.append(
                f"  [{e.status}] {e.citation_key}: "
                f"conf={e.confidence_score:.2f} "
                f"doi={e.doi or '-'} "
                f"journal={e.journal or '-'}"
            )
        lines.append("")
        lines.append(
            f"Total: {len(self.entries)} entries — "
            f"{self.enriched_count()} enriched / "
            f"{self.kept_todo_count()} kept TODO / "
            f"{self.skipped_count()} no-TODO (already had journal)"
        )
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Enrichment core
# ---------------------------------------------------------------------------


_TARGET_FIELDS = ("journal", "volume", "issue", "pages", "doi")


def _bibtex_escape_value(text: str) -> str:
    """Escape BibTeX-hostile characters inside a field value.

    BibTeX honors the same TeX escape rules as the manuscript body. We
    escape ``&`` and ``%`` which appear in real journal names like
    "International Journal of Finance & Economics" — without escaping
    BibTeX would treat ``&`` as a special character and break compilation.
    """
    return text.replace("\\", r"\textbackslash{}").replace("&", r"\&").replace(
        "%", r"\%"
    )


def _apply_result_to_entry(
    entry: BibEntry, result: CrossRefResult
) -> BibEntry:
    """Return a new BibEntry with CrossRef fields filled in (non-destructive).

    Only fills fields that are empty or hold a ``[TODO: ...]`` placeholder.
    Never overwrites author / title / year — those are the researcher's
    canonical version.
    """
    new_fields = dict(entry.fields)
    if result.journal and (
        "journal" not in new_fields or new_fields["journal"].startswith("[TODO:")
    ):
        new_fields["journal"] = _bibtex_escape_value(result.journal)
    if result.volume and not new_fields.get("volume"):
        new_fields["volume"] = result.volume
    if result.issue and not new_fields.get("issue"):
        new_fields["issue"] = result.issue
    if result.pages and not new_fields.get("pages"):
        # CrossRef uses ``page = "123-145"``; BibTeX convention is the
        # same. Normalize en-dash → ASCII double-hyphen for booktabs-friendly
        # rendering.
        new_fields["pages"] = result.pages.replace("–", "--").replace(
            "-", "--"
        ).replace("----", "--")
    if result.doi and not new_fields.get("doi"):
        new_fields["doi"] = result.doi
    return BibEntry(
        entry_type=entry.entry_type,
        citation_key=entry.citation_key,
        fields=new_fields,
    )


def _entry_has_any_todo(entry: BibEntry) -> bool:
    """True if any of the target enrichment fields is empty or TODO."""
    for f in _TARGET_FIELDS:
        if f not in entry.fields:
            return True
        if entry.fields[f].startswith("[TODO:"):
            return True
    return False


def enrich_references_bib(
    input_bib_path: Path | None = None,
    output_bib_path: Path | None = None,
    *,
    min_confidence: float = DEFAULT_MIN_CONFIDENCE,
    cache_path: Path | None = None,
    client: CrossRefClient | None = None,
    write_output: bool = True,
) -> EnrichmentReport:
    """Enrich ``input_bib_path`` against CrossRef and write ``output_bib_path``.

    Parameters
    ----------
    input_bib_path:
        BibTeX source to enrich (default ``paper/references.bib``).
    output_bib_path:
        Destination for the enriched BibTeX (default
        ``paper/references.enriched.bib``).
    min_confidence:
        Confidence threshold below which CrossRef matches are discarded
        and the entry retains its original placeholder.
    cache_path:
        On-disk cache file (default ``cache/crossref_cache.json``).
    client:
        Optional :class:`CrossRefClient` (mainly for tests). Defaults to
        the production client.
    write_output:
        If False (e.g. ``--dry-run``), the report is computed but no
        file is written.

    Returns
    -------
    EnrichmentReport
        Per-entry status + aggregate counts.
    """
    input_bib_path = input_bib_path or _default_input_bib()
    output_bib_path = output_bib_path or _default_output_bib()
    cache_path = cache_path or _default_cache_path()
    client = client or CrossRefClient()

    bib_text = input_bib_path.read_text(encoding="utf-8")
    entries = _parse_bib(bib_text)

    cache = CrossRefCache(path=cache_path)
    cache.load()

    report = EnrichmentReport()
    enriched_entries: list[BibEntry] = []

    for entry in entries:
        if not _entry_has_any_todo(entry):
            # Entry already has everything; keep it as-is.
            report.entries.append(
                EntryEnrichment(
                    citation_key=entry.citation_key,
                    title=entry.title(),
                    status="skipped_no_todo",
                    confidence_score=1.0,
                    doi=entry.fields.get("doi", ""),
                    journal=entry.fields.get("journal", ""),
                )
            )
            enriched_entries.append(entry)
            continue

        cached = cache.get(entry)
        if cached == "miss":
            # Previously cached as no-match; don't re-query.
            result: CrossRefResult | None = None
        elif isinstance(cached, CrossRefResult):
            result = cached
        else:
            try:
                result = client.query(
                    authors=entry.author(),
                    year=entry.year_int(),
                    title=entry.title(),
                )
            except Exception as exc:  # noqa: BLE001
                # Defense-in-depth: the client already swallows
                # RequestException, but a malformed JSON or programmer
                # bug shouldn't kill the whole run.
                logger.warning(
                    "CrossRef query crashed for %s: %s",
                    entry.citation_key,
                    exc,
                )
                result = None
            cache.put(entry, result)

        if result is None:
            report.entries.append(
                EntryEnrichment(
                    citation_key=entry.citation_key,
                    title=entry.title(),
                    status="kept_todo_no_match",
                    confidence_score=0.0,
                )
            )
            enriched_entries.append(entry)
            continue

        if result.confidence_score < min_confidence:
            report.entries.append(
                EntryEnrichment(
                    citation_key=entry.citation_key,
                    title=entry.title(),
                    status="kept_todo_low_confidence",
                    confidence_score=result.confidence_score,
                    doi=result.doi,
                    journal=result.journal,
                )
            )
            enriched_entries.append(entry)
            continue

        # Confident match — apply.
        new_entry = _apply_result_to_entry(entry, result)
        enriched_entries.append(new_entry)
        report.entries.append(
            EntryEnrichment(
                citation_key=entry.citation_key,
                title=entry.title(),
                status="enriched",
                confidence_score=result.confidence_score,
                doi=result.doi,
                journal=result.journal,
            )
        )

    cache.save()

    if write_output:
        output_text = "\n\n".join(_format_entry(e) for e in enriched_entries) + "\n"
        output_bib_path.parent.mkdir(parents=True, exist_ok=True)
        output_bib_path.write_text(output_text, encoding="utf-8")

    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="index-inclusion-enrich-bib",
        description=(
            "Enrich paper/references.bib with full CrossRef bibliographic "
            "data (journal, volume, issue, pages, DOI). Original "
            "author/title/year are never overwritten. Low-confidence "
            "matches (< --min-confidence) keep the original [TODO: ...] "
            "placeholder."
        ),
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="Source BibTeX file (default: paper/references.bib).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Destination BibTeX (default: paper/references.enriched.bib).",
    )
    parser.add_argument(
        "--min-confidence",
        type=float,
        default=DEFAULT_MIN_CONFIDENCE,
        help=(
            "Confidence threshold (0.0–1.0); below this the entry keeps "
            f"its [TODO: ...] placeholder (default {DEFAULT_MIN_CONFIDENCE})."
        ),
    )
    parser.add_argument(
        "--cache-path",
        type=Path,
        default=None,
        help="CrossRef cache JSON file (default: cache/crossref_cache.json).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would change without writing the output file.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="%(levelname)s %(name)s: %(message)s"
    )
    args = _build_arg_parser().parse_args(argv)

    report = enrich_references_bib(
        input_bib_path=args.input,
        output_bib_path=args.output,
        min_confidence=args.min_confidence,
        cache_path=args.cache_path,
        write_output=not args.dry_run,
    )

    logger.info(report.as_text())
    if args.dry_run:
        logger.info("(dry-run: no output file written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
